{{- if and .Values.controller.enabled .Values.controller.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (printf "%s-controller" (include "medusa.fullname" .)) .Values.controller.serviceAccount.name }}
  labels:
    app.kubernetes.io/name: {{ include "medusa.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: controller
  annotations:
    {{- range $k, $v := .Values.controller.serviceAccount.annotations }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
{{- end -}}
