{{- if .Values.redis.enabled -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "medusa.fullname" . }}-redis
  labels:
    app.kubernetes.io/name: {{ include "medusa.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: redis
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  serviceName: {{ include "medusa.fullname" . }}-redis
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "medusa.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: redis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "medusa.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: redis
    spec:
      securityContext:
        runAsUser: {{ .Values.redis.securityContext.runAsUser }}
        runAsGroup: {{ .Values.redis.securityContext.runAsGroup }}
        fsGroup: {{ .Values.redis.securityContext.fsGroup }}
        seccompProfile:
          type: {{ .Values.redis.securityContext.seccompProfile.type }}
      containers:
        - name: redis
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          command: ["redis-server", "--appendonly", "yes"]
          securityContext:
            allowPrivilegeEscalation: {{ .Values.redis.securityContext.allowPrivilegeEscalation }}
            capabilities:
              {{- toYaml .Values.redis.securityContext.capabilities | nindent 12 }}
          ports:
            - containerPort: {{ .Values.redis.service.port }}
              name: tcp-redis
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
          volumeMounts:
            - name: redis-data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes:
          {{- toYaml .Values.redis.persistence.accessModes | nindent 10 }}
        resources:
          requests:
            storage: {{ .Values.redis.persistence.size }}
        {{- if .Values.redis.persistence.storageClass }}
        storageClassName: {{ .Values.redis.persistence.storageClass }}
        {{- end }}
{{- end -}}
