{{- if and (eq .Values.secrets.strategy "inline") .Values.secrets.inline }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  labels:
    app.kubernetes.io/name: {{ include "medusa.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: secrets
  annotations:
    medusa.security/description: "Inline development secrets. Never enable in production clusters."
type: Opaque
stringData:
  {{- range $k, $v := .Values.secrets.inline }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
