{{- if and (eq .Values.secrets.strategy "externalSecret") .Values.secrets.externalSecret.secretStoreName }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.secrets.name }}
  labels:
    app.kubernetes.io/name: {{ include "medusa.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: secrets
  annotations:
    medusa.security/description: "ExternalSecret binding Medusa application credentials from central secret store."
spec:
  refreshInterval: {{ default "1h" .Values.secrets.externalSecret.refreshInterval }}
  secretStoreRef:
    kind: {{ .Values.secrets.externalSecret.secretStoreKind }}
    name: {{ .Values.secrets.externalSecret.secretStoreName }}
  target:
    name: {{ .Values.secrets.name }}
    creationPolicy: Owner
  data:
    {{- range .Values.secrets.externalSecret.data }}
    - {{- toYaml . | nindent 6 }}
    {{- end }}
{{- end }}
