{{- if and (eq .Values.secrets.strategy "sealedSecret") .Values.secrets.sealedSecret.encryptedData }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.secrets.name }}
  labels:
    app.kubernetes.io/name: {{ include "medusa.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: secrets
  annotations:
    medusa.security/description: "SealedSecret envelope for Medusa credentials."
spec:
  encryptedData:
    {{- range $k, $v := .Values.secrets.sealedSecret.encryptedData }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
  template:
    metadata:
      name: {{ .Values.secrets.name }}
      annotations:
        {{- range $k, $v := .Values.secrets.sealedSecret.annotations }}
        {{ $k }}: {{ $v | quote }}
        {{- end }}
    type: Opaque
{{- end }}
