import type { Metadata } from 'next';
import './globals.css';
import { LayoutShell } from '@/components/LayoutShell';

export const metadata: Metadata = {
  title: 'Medusa Operations Console',
  description:
    'Operations console for monitoring automated pentest scans and findings generated by the Medusa controller.'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-surface-subtle">
        <LayoutShell>{children}</LayoutShell>
      </body>
    </html>
  );
}
