"""Ensure baseline principals exist with deterministic API keys for local dev."""

from __future__ import annotations

import argparse
import json
import logging
import secrets
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Iterable, Mapping, MutableMapping, Optional

from sqlalchemy.orm import Session

from controller.db.models import PrincipalCredential
from controller.db.session import session_scope
from controller.main import (
    CREDENTIAL_SOURCE_MANUAL,
    DEFAULT_ADMIN_ROLES,
    DEFAULT_ANALYST_ROLES,
    _hash_secret,
)

LOGGER = logging.getLogger(__name__)


@dataclass(frozen=True)
class PrincipalSeed:
    """Configuration describing a principal that must exist."""

    subject: str
    roles: Iterable[str]
    description: str
    env_var: str


PRINCIPALS: tuple[PrincipalSeed, ...] = (
    PrincipalSeed(
        subject="svc-admin",
        roles=DEFAULT_ADMIN_ROLES,
        description="Controller administrator with full access",
        env_var="MEDUSA_ADMIN_API_KEY",
    ),
    PrincipalSeed(
        subject="svc-analyst",
        roles=DEFAULT_ANALYST_ROLES,
        description="Read-only analyst for dashboard access",
        env_var="MEDUSA_ANALYST_API_KEY",
    ),
)


def _load_env_file(path: Path) -> Dict[str, str]:
    """Parse an env-style file into a dictionary."""

    if not path.exists():
        return {}

    values: Dict[str, str] = {}
    for line in path.read_text().splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if "=" not in stripped:
            continue
        key, value = stripped.split("=", 1)
        values[key.strip()] = value.strip()
    return values


def _write_env_file(path: Path, values: Mapping[str, str]) -> None:
    """Persist API keys in a dotenv-compatible format."""

    path.parent.mkdir(parents=True, exist_ok=True)
    lines = ["# Generated by controller.scripts.seed_principals"]
    for key, value in sorted(values.items()):
        lines.append(f"{key}={value}")
    path.write_text("\n".join(lines) + "\n")
    path.chmod(0o600)


def _ensure_principal(
    session: Session,
    seed: PrincipalSeed,
    existing_secrets: Mapping[str, str],
    persisted_secrets: MutableMapping[str, str],
) -> Optional[str]:
    """Insert or update a principal credential record.

    Returns the generated secret if a new value had to be created.
    """

    credential = (
        session.query(PrincipalCredential)
        .filter(
            PrincipalCredential.subject == seed.subject,
            PrincipalCredential.revoked_at.is_(None),
        )
        .one_or_none()
    )

    known_secret = existing_secrets.get(seed.env_var)
    generated_secret: Optional[str] = None

    if credential is None:
        secret = known_secret or secrets.token_urlsafe(32)
        credential = PrincipalCredential(
            subject=seed.subject,
            auth_method="api_key",
            key_hash=_hash_secret(secret),
            roles=list(dict.fromkeys(seed.roles)),
            description=seed.description,
            source=CREDENTIAL_SOURCE_MANUAL,
        )
        session.add(credential)
        generated_secret = secret if secret != known_secret else None
        persisted_secrets[seed.env_var] = secret
        LOGGER.info("Created principal %s", seed.subject)
        return generated_secret

    if credential.auth_method != "api_key":
        raise RuntimeError(
            f"Principal {seed.subject} exists with auth_method={credential.auth_method}"
        )

    if credential.source != CREDENTIAL_SOURCE_MANUAL:
        credential.source = CREDENTIAL_SOURCE_MANUAL

    # Ensure the principal retains baseline roles for local workflows.
    desired_roles = list(dict.fromkeys(seed.roles))
    if sorted(credential.roles or []) != sorted(desired_roles):
        credential.roles = desired_roles
        LOGGER.info("Updated roles for principal %s", seed.subject)

    if credential.key_hash:
        if known_secret:
            expected_hash = _hash_secret(known_secret)
            if credential.key_hash != expected_hash:
                credential.key_hash = expected_hash
                LOGGER.warning(
                    "Reset API key hash for %s to align with env file",
                    seed.subject,
                )
            persisted_secrets[seed.env_var] = known_secret
            return None
        # rotate the key to keep the environment in sync
        secret = secrets.token_urlsafe(32)
        credential.key_hash = _hash_secret(secret)
        generated_secret = secret
        persisted_secrets[seed.env_var] = secret
        LOGGER.warning(
            "Rotated API key for %s because no cleartext secret was available",
            seed.subject,
        )
        return generated_secret

    # credential.key_hash missing; populate from known secret or rotate
    secret = known_secret or secrets.token_urlsafe(32)
    credential.key_hash = _hash_secret(secret)
    generated_secret = secret if secret != known_secret else None
    persisted_secrets[seed.env_var] = secret
    LOGGER.info("Provisioned missing key material for %s", seed.subject)
    return generated_secret


def seed_principals(env_file: Optional[Path] = None) -> Dict[str, str]:
    """Ensure admin and analyst principals exist, returning any new secrets."""

    env_values: Mapping[str, str] = {}
    if env_file is not None:
        env_values = _load_env_file(env_file)

    created_secrets: Dict[str, str] = {}
    persisted_secrets: Dict[str, str] = dict(env_values)

    with session_scope() as session:
        for seed in PRINCIPALS:
            generated = _ensure_principal(session, seed, env_values, persisted_secrets)
            if generated is not None:
                created_secrets[seed.env_var] = generated

    if env_file is not None and persisted_secrets:
        _write_env_file(env_file, persisted_secrets)

    return created_secrets


def main() -> None:
    parser = argparse.ArgumentParser(description="Seed required principal credentials")
    parser.add_argument(
        "--env-file",
        type=Path,
        default=Path("/var/lib/medusa/principal_credentials.env"),
        help="Path to write the generated API keys for dependent services",
    )
    parser.add_argument(
        "--json", action="store_true", help="Print JSON payload of generated secrets"
    )
    args = parser.parse_args()

    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")

    created = seed_principals(env_file=args.env_file)
    if args.json:
        print(json.dumps(created))
    elif created:
        print(json.dumps(created))


if __name__ == "__main__":
    main()
