# Development environment defaults for the Medusa platform.
project_name                 = "medusa"
environment                  = "dev"
aws_profile                  = "medusa-dev"
aws_region                   = "us-east-1"
cluster_name                 = "medusa-dev"
state_bucket                 = "medusa-dev-terraform-state"
state_dynamodb_table         = "medusa-terraform-locks"
state_key_prefix             = "dev"
kubeconfig_path              = "~/.kube/config"
kubeconfig_context           = "medusa-dev"
helm_registry_config         = "~/.docker/config.json"
container_registry_server    = "ghcr.io"
container_registry_username  = "medusa-dev-bot"
container_registry_password  = "REPLACE_WITH_OIDC_TOKEN"
helm_repository_url          = "oci://ghcr.io/medusa/charts"
helm_repository_username     = "medusa-dev-bot"
helm_repository_password     = "REPLACE_WITH_OIDC_TOKEN"
